// <auto-generated/>
#pragma warning disable 1591
namespace Alife.Function.Speech
{
    using global::System;
    using global::System.Collections.Generic;
    using global::System.IO;
    using global::System.Linq;
    using global::System.Linq.Expressions;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    using global::Microsoft.AspNetCore.Components.Rendering;
    using global::AntDesign;

    public partial class MiniMaxTTSUI :
        Alife.Framework.ModuleUIBase<MiniMaxTTSModel, MiniMaxTTSConfig>
    {
        // ── 渲染序列号（class field 避免 ref 参数在 lambda 中不可用）──
        int _s;

        // ── 克隆 UI 状态 ──
        string _cloneAudioPath = "";
        string _cloneVoiceName = "";
        string _clonePromptPath = "";
        string _clonePromptText = "";
        string? _cloneStatus = null;
        bool _isCloning = false;

        // ═══════════════════════════════════════════
        //  音色选项（下拉选用）
        // ═══════════════════════════════════════════

        class VoiceItem
        {
            public string Label { get; init; } = "";
            public string Value { get; init; } = "";
        }

        static readonly VoiceItem[] AllVoices = new[]
        {
            // ═══════════════════ 中文（普通话）58个 ═══════════════════

            // ── 基础8音 ──
            new VoiceItem { Label = "【中文】青涩青年", Value = "male-qn-qingse" },
            new VoiceItem { Label = "【中文】精英青年", Value = "male-qn-jingying" },
            new VoiceItem { Label = "【中文】霸道青年", Value = "male-qn-badao" },
            new VoiceItem { Label = "【中文】青年大学生", Value = "male-qn-daxuesheng" },
            new VoiceItem { Label = "【中文】少女音色", Value = "female-shaonv" },
            new VoiceItem { Label = "【中文】御姐音色", Value = "female-yujie" },
            new VoiceItem { Label = "【中文】成熟女性", Value = "female-chengshu" },
            new VoiceItem { Label = "【中文】甜美女性", Value = "female-tianmei" },

            // ── 精品/beta 8音 ──
            new VoiceItem { Label = "【中文】青涩青年-beta", Value = "male-qn-qingse-jingpin" },
            new VoiceItem { Label = "【中文】精英青年-beta", Value = "male-qn-jingying-jingpin" },
            new VoiceItem { Label = "【中文】霸道青年-beta", Value = "male-qn-badao-jingpin" },
            new VoiceItem { Label = "【中文】青年大学生-beta", Value = "male-qn-daxuesheng-jingpin" },
            new VoiceItem { Label = "【中文】少女音色-beta", Value = "female-shaonv-jingpin" },
            new VoiceItem { Label = "【中文】御姐音色-beta", Value = "female-yujie-jingpin" },
            new VoiceItem { Label = "【中文】成熟女性-beta", Value = "female-chengshu-jingpin" },
            new VoiceItem { Label = "【中文】甜美女性-beta", Value = "female-tianmei-jingpin" },

            // ── 角色音14个 ──
            new VoiceItem { Label = "【中文】聪明男童", Value = "clever_boy" },
            new VoiceItem { Label = "【中文】可爱男童", Value = "cute_boy" },
            new VoiceItem { Label = "【中文】萌萌女童", Value = "lovely_girl" },
            new VoiceItem { Label = "【中文】卡通猪小琪", Value = "cartoon_pig" },
            new VoiceItem { Label = "【中文】病娇弟弟", Value = "bingjiao_didi" },
            new VoiceItem { Label = "【中文】俊朗男友", Value = "junlang_nanyou" },
            new VoiceItem { Label = "【中文】纯真学弟", Value = "chunzhen_xuedi" },
            new VoiceItem { Label = "【中文】冷淡学长", Value = "lengdan_xiongzhang" },
            new VoiceItem { Label = "【中文】霸道少爷", Value = "badao_shaoye" },
            new VoiceItem { Label = "【中文】甜心小玲", Value = "tianxin_xiaoling" },
            new VoiceItem { Label = "【中文】俏皮萌妹", Value = "qiaopi_mengmei" },
            new VoiceItem { Label = "【中文】妩媚御姐", Value = "wumei_yujie" },
            new VoiceItem { Label = "【中文】嗲嗲学妹", Value = "diadia_xuemei" },
            new VoiceItem { Label = "【中文】淡雅学姐", Value = "danya_xuejie" },

            // ── 风格音28个 ──
            new VoiceItem { Label = "【中文】沉稳高管（Reliable Executive）", Value = "Chinese (Mandarin)_Reliable_Executive" },
            new VoiceItem { Label = "【中文】新闻女声（News Anchor）", Value = "Chinese (Mandarin)_News_Anchor" },
            new VoiceItem { Label = "【中文】傲娇御姐（Mature Woman）", Value = "Chinese (Mandarin)_Mature_Woman" },
            new VoiceItem { Label = "【中文】不羁青年（Unrestrained）", Value = "Chinese (Mandarin)_Unrestrained_Young_Man" },
            new VoiceItem { Label = "【中文】嚣张小姐（Arrogant Miss）", Value = "Arrogant_Miss" },
            new VoiceItem { Label = "【中文】机械战甲（Robot Armor）", Value = "Robot_Armor" },
            new VoiceItem { Label = "【中文】热心大婶（Kind-hearted Antie）", Value = "Chinese (Mandarin)_Kind-hearted_Antie" },
            new VoiceItem { Label = "【中文】港普空姐（HK Attendant）", Value = "Chinese (Mandarin)_HK_Flight_Attendant" },
            new VoiceItem { Label = "【中文】搞笑大爷（Humorous Elder）", Value = "Chinese (Mandarin)_Humorous_Elder" },
            new VoiceItem { Label = "【中文】温润男声（Gentleman）", Value = "Chinese (Mandarin)_Gentleman" },
            new VoiceItem { Label = "【中文】温暖闺蜜（Warm Bestie）", Value = "Chinese (Mandarin)_Warm_Bestie" },
            new VoiceItem { Label = "【中文】播报男声（Male Announcer）", Value = "Chinese (Mandarin)_Male_Announcer" },
            new VoiceItem { Label = "【中文】甜美女声（Sweet Lady）", Value = "Chinese (Mandarin)_Sweet_Lady" },
            new VoiceItem { Label = "【中文】南方小哥（Southern Youth）", Value = "Chinese (Mandarin)_Southern_Young_Man" },
            new VoiceItem { Label = "【中文】阅历姐姐（Wise Woman）", Value = "Chinese (Mandarin)_Wise_Women" },
            new VoiceItem { Label = "【中文】温润青年（Gentle Youth）", Value = "Chinese (Mandarin)_Gentle_Youth" },
            new VoiceItem { Label = "【中文】温暖少女（Warm Girl）", Value = "Chinese (Mandarin)_Warm_Girl" },
            new VoiceItem { Label = "【中文】花甲奶奶（Kind Elder）", Value = "Chinese (Mandarin)_Kind-hearted_Elder" },
            new VoiceItem { Label = "【中文】憨憨萌兽（Cute Spirit）", Value = "Chinese (Mandarin)_Cute_Spirit" },
            new VoiceItem { Label = "【中文】电台男主播（Radio Host）", Value = "Chinese (Mandarin)_Radio_Host" },
            new VoiceItem { Label = "【中文】抒情男声（Lyrical Voice）", Value = "Chinese (Mandarin)_Lyrical_Voice" },
            new VoiceItem { Label = "【中文】率真弟弟（Straightforward）", Value = "Chinese (Mandarin)_Straightforward_Boy" },
            new VoiceItem { Label = "【中文】真诚青年（Sincere Adult）", Value = "Chinese (Mandarin)_Sincere_Adult" },
            new VoiceItem { Label = "【中文】温柔学姐（Gentle Senior）", Value = "Chinese (Mandarin)_Gentle_Senior" },
            new VoiceItem { Label = "【中文】嘴硬竹马（Stubborn Friend）", Value = "Chinese (Mandarin)_Stubborn_Friend" },
            new VoiceItem { Label = "【中文】清脆少女（Crisp Girl）", Value = "Chinese (Mandarin)_Crisp_Girl" },
            new VoiceItem { Label = "【中文】清澈邻家弟弟（Pure Boy）", Value = "Chinese (Mandarin)_Pure-hearted_Boy" },
            new VoiceItem { Label = "【中文】柔和少女（Soft Girl）", Value = "Chinese (Mandarin)_Soft_Girl" },

            // ═══════════════════ 英文 16个 ═══════════════════
            new VoiceItem { Label = "【EN】Santa Claus", Value = "Santa_Claus" },
            new VoiceItem { Label = "【EN】Grinch", Value = "Grinch" },
            new VoiceItem { Label = "【EN】Rudolph", Value = "Rudolph" },
            new VoiceItem { Label = "【EN】Arnold", Value = "Arnold" },
            new VoiceItem { Label = "【EN】Charming Santa", Value = "Charming_Santa" },
            new VoiceItem { Label = "【EN】Charming Lady", Value = "Charming_Lady" },
            new VoiceItem { Label = "【EN】Sweet Girl", Value = "Sweet_Girl" },
            new VoiceItem { Label = "【EN】Cute Elf", Value = "Cute_Elf" },
            new VoiceItem { Label = "【EN】Attractive Girl", Value = "Attractive_Girl" },
            new VoiceItem { Label = "【EN】Serene Woman", Value = "Serene_Woman" },
            new VoiceItem { Label = "【EN】Trustworthy Man", Value = "English_Trustworthy_Man" },
            new VoiceItem { Label = "【EN】Graceful Lady", Value = "English_Graceful_Lady" },
            new VoiceItem { Label = "【EN】Aussie Bloke", Value = "English_Aussie_Bloke" },
            new VoiceItem { Label = "【EN】Whispering Girl", Value = "English_Whispering_girl" },
            new VoiceItem { Label = "【EN】Diligent Man", Value = "English_Diligent_Man" },
            new VoiceItem { Label = "【EN】Gentle-voiced Man", Value = "English_Gentle-voiced_man" },
        };

        static readonly (string label, string id)[] ChineseQuickVoices = {
            ("温暖闺蜜", "Chinese (Mandarin)_Warm_Bestie"),
            ("少女音色", "female-shaonv"),
            ("甜美女性", "female-tianmei"),
            ("霸道青年", "male-qn-badao"),
            ("新闻女声", "Chinese (Mandarin)_News_Anchor"),
            ("甜美女声", "Chinese (Mandarin)_Sweet_Lady"),
            ("温暖少女", "Chinese (Mandarin)_Warm_Girl"),
        };

        static readonly (string label, string id)[] EnglishQuickVoices = {
            ("Sweet Girl", "Sweet_Girl"),
            ("Charming Lady", "Charming_Lady"),
            ("Trustworthy Man", "English_Trustworthy_Man"),
            ("Graceful Lady", "English_Graceful_Lady"),
            ("Aussie Bloke", "English_Aussie_Bloke"),
            ("Serene Woman", "Serene_Woman"),
        };

        static readonly string[] Models = {
            "speech-2.8-turbo",   // 最新快速版 $60/M
            "speech-2.8-hd",      // 最新高清版 $100/M
            "speech-2.6-turbo",   // 旧版快速
            "speech-2.6-hd",      // 旧版高清
            "speech-02-turbo",    // 旧版快速（别名）
            "speech-02-hd",       // 旧版高清（别名）
            "speech-01-hd",       // 更早版本
            "speech-01-turbo",    // 更早版本
        };
        static readonly string[] AudioFormats = { "mp3", "wav", "flac", "pcm" };
        static readonly (string label, string val)[] Emotions = {
            ("无（不发送）", ""),
            ("高兴 happy", "happy"),
            ("伤心 sad", "sad"),
            ("生气 angry", "angry"),
            ("害怕 fearful", "fearful"),
            ("惊讶 surprised", "surprised"),
            ("厌恶 disgusted", "disgusted"),
            ("中性 calm", "calm"),
            ("生动 fluent (2.6 only)", "fluent"),
            ("低语 whisper (2.6 only)", "whisper"),
        };

        // ── 克隆按钮异步处理 ──
        async Task OnCloneClickAsync()
        {
            if (_isCloning) return;
            if (string.IsNullOrWhiteSpace(_cloneAudioPath))
            {
                _cloneStatus = "请填写源音频文件路径";
                return;
            }
            if (string.IsNullOrWhiteSpace(_cloneVoiceName))
            {
                _cloneStatus = "请填写音色名称";
                return;
            }

            _isCloning = true;
            _cloneStatus = "正在上传并克隆音色...";
            StateHasChanged();

            try
            {
                var cfg = Configuration;
                var result = await MiniMaxTTSModel.CloneVoiceStaticAsync(
                    cfg,
                    _cloneAudioPath,
                    _cloneVoiceName,
                    string.IsNullOrWhiteSpace(_clonePromptPath) ? null : _clonePromptPath,
                    string.IsNullOrWhiteSpace(_clonePromptText) ? null : _clonePromptText);

                _cloneStatus = result == null
                    ? $"✅ 克隆成功！已自动切换音色为「{_cloneVoiceName}」"
                    : $"❌ {result}";
            }
            catch (Exception ex)
            {
                _cloneStatus = $"❌ 克隆异常：{ex.Message}";
            }
            finally
            {
                _isCloning = false;
                StateHasChanged();
            }
        }

        // ═══════════════════════════════════════════
        //  BuildRenderTree
        // ═══════════════════════════════════════════

        protected override void BuildRenderTree(RenderTreeBuilder b)
        {
            var cfg = Configuration;
            if (cfg == null) return;
            _s = 0;

            // ── 外层容器 ──
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "background:#fff;padding:20px;border-radius:8px;max-width:640px");

            // ── 标题 ──
            b.OpenComponent<Title>(_s++);
            b.AddComponentParameter(_s++, "Level", 4);
            b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
            {
                b2.AddContent(_s++, "MiniMax TTS（在线）");
            }));
            b.CloseComponent();

            b.OpenComponent<Text>(_s++);
            b.AddComponentParameter(_s++, "Type", TextElementType.Secondary);
            b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
            {
                b2.AddContent(_s++, "调用 MiniMax T2A V2 API 进行在线语音合成，支持 300+ 音色及音色克隆。");
            }));
            b.CloseComponent();

            // ═══════════ API 认证 ═══════════
            RenderInputField(b, "API Key", cfg.ApiKey, v => cfg.ApiKey = v,
                "Bearer Token", AntDesign.InputType.Password);
            RenderInputField(b, "API 地址", cfg.BaseUrl, v => cfg.BaseUrl = v,
                "https://api.minimaxi.com", null);

            // ═══════════ 模型 & 音频格式 ═══════════
            RenderSelectField(b, "模型", cfg.Model, v => cfg.Model = v, Models);
            RenderSelectField(b, "音频格式", cfg.AudioFormat, v => cfg.AudioFormat = v, AudioFormats);

            // ═══════════ 音色（下拉选 + 文本框 + 快捷按钮）═══════════
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "margin-top:12px");

            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "font-size:13px;color:#333;margin-bottom:4px");
            b.AddContent(_s++, "音色 ID");
            b.CloseElement();

            // 可搜索下拉选
            b.OpenComponent<Select<string, string>>(_s++);
            b.AddComponentParameter(_s++, "Value", cfg.VoiceId);
            b.AddComponentParameter(_s++, "ValueChanged",
                EventCallback.Factory.Create<string>(this, v => cfg.VoiceId = v));
            b.AddComponentParameter(_s++, "Placeholder", "搜索或选择系统音色…");
            b.AddComponentParameter(_s++, "AllowSearch", true);
            b.AddComponentParameter(_s++, "Style", "width:100%");
            b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
            {
                int _ = _s;
                foreach (var v in AllVoices)
                {
                    b2.OpenComponent<SelectOption<string, string>>(_++);
                    b2.AddComponentParameter(_++, "Value", v.Value);
                    b2.AddComponentParameter(_++, "Label", v.Label);
                    b2.CloseComponent();
                }
            }));
            b.CloseComponent();

            // 手动输入框
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "margin-top:4px");
            b.OpenComponent<Input<string>>(_s++);
            b.AddComponentParameter(_s++, "Value", cfg.VoiceId);
            b.AddComponentParameter(_s++, "ValueChanged",
                EventCallback.Factory.Create<string>(this, v => cfg.VoiceId = v));
            b.AddComponentParameter(_s++, "Placeholder", "或在此手动输入自定义音色 ID（克隆音色名）");
            b.CloseComponent();
            b.CloseElement();

            b.CloseElement(); // 音色 ID 区域

            // 快捷按钮
            RenderVoiceButtons(b, "中文快捷", ChineseQuickVoices);
            RenderVoiceButtons(b, "英文快捷", EnglishQuickVoices);

            // ═══════════ 语音参数 ═══════════
            RenderSliderField(b, "语速", cfg.Speed, v => cfg.Speed = v, 0.5, 2.0, 0.1, "x");
            RenderSliderField(b, "音量（1~10）", cfg.Volume, v => cfg.Volume = (int)v, 1, 10, 1, "");
            RenderSliderField(b, "音调（-12~12）", cfg.Pitch, v => cfg.Pitch = (int)v, -12, 12, 1, "");

            // ═══════════ 情感 ═══════════
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "margin-top:12px");
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "font-size:13px;color:#333;margin-bottom:4px");
            b.AddContent(_s++, "情感");
            b.CloseElement();
            b.OpenComponent<Select<string, string>>(_s++);
            b.AddComponentParameter(_s++, "Value", cfg.Emotion);
            b.AddComponentParameter(_s++, "ValueChanged",
                EventCallback.Factory.Create<string>(this, v => cfg.Emotion = v));
            b.AddComponentParameter(_s++, "Style", "width:100%");
            b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
            {
                int _ = _s;
                foreach (var e in Emotions)
                {
                    b2.OpenComponent<SelectOption<string, string>>(_++);
                    b2.AddComponentParameter(_++, "Value", e.val);
                    b2.AddComponentParameter(_++, "Label", e.label);
                    b2.CloseComponent();
                }
            }));
            b.CloseComponent();
            b.CloseElement();

            // ═══════════ 音色克隆 ═══════════
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "margin-top:24px;border-top:1px solid #e8e8e8;padding-top:16px");

            b.OpenComponent<Title>(_s++);
            b.AddComponentParameter(_s++, "Level", 5);
            b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
            {
                b2.AddContent(_s++, "🎤 音色克隆");
            }));
            b.CloseComponent();

            b.OpenComponent<Text>(_s++);
            b.AddComponentParameter(_s++, "Type", TextElementType.Secondary);
            b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
            {
                b2.AddContent(_s++, "上传一段音频（10秒~5分钟, mp3/m4a/wav, ≤20MB），克隆出专属音色，之后直接在「音色 ID」中使用。");
            }));
            b.CloseComponent();

            RenderInputField(b, "源音频文件路径 *", _cloneAudioPath, v => _cloneAudioPath = v,
                @"D:\音频\我的声音样本.mp3  (10秒~5分钟, mp3/m4a/wav)", null);
            RenderInputField(b, "自定义音色名称 *", _cloneVoiceName, v => _cloneVoiceName = v,
                "例如: my_voice_01（克隆成功后自动选中此音色）", null);
            RenderInputField(b, "提示音频（可选）", _clonePromptPath, v => _clonePromptPath = v,
                @"D:\音频\提示样本.mp3  (<8秒, 用于提高克隆相似度)", null);
            RenderInputField(b, "提示文本（可选）", _clonePromptText, v => _clonePromptText = v,
                "提示音频中说的话的转写文本", null);

            // 克隆按钮 + 状态
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "display:flex;align-items:center;gap:12px;margin-top:12px");

            b.OpenComponent<Button>(_s++);
            b.AddComponentParameter(_s++, "Type", AntDesign.ButtonType.Primary);
            b.AddComponentParameter(_s++, "Loading", _isCloning);
            b.AddComponentParameter(_s++, "Disabled", _isCloning);
            b.AddComponentParameter(_s++, "OnClick",
                EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(
                    this, async (args) => await OnCloneClickAsync()));
            b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
            {
                b2.AddContent(_s++, "开始克隆");
            }));
            b.CloseComponent();

            if (_cloneStatus != null)
            {
                b.OpenComponent<Text>(_s++);
                b.AddComponentParameter(_s++, "Type",
                    _cloneStatus.StartsWith("✅")
                        ? TextElementType.Success
                        : _cloneStatus.StartsWith("正在")
                            ? TextElementType.Warning
                            : TextElementType.Danger);
                b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
                {
                    b2.AddContent(_s++, _cloneStatus);
                }));
                b.CloseComponent();
            }
            b.CloseElement(); // 按钮行

            b.CloseElement(); // 克隆区域

            b.CloseElement(); // 外层 div
        }

        // ═══════════════════════════════════════════
        //  Render Helpers
        // ═══════════════════════════════════════════

        void RenderInputField(RenderTreeBuilder b, string label, string value,
            Action<string> setter, string placeholder, AntDesign.InputType? inputType)
        {
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "margin-top:12px");
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "font-size:13px;color:#333;margin-bottom:4px");
            b.AddContent(_s++, label);
            b.CloseElement();
            b.OpenComponent<Input<string>>(_s++);
            b.AddComponentParameter(_s++, "Value", value);
            b.AddComponentParameter(_s++, "ValueChanged",
                EventCallback.Factory.Create<string>(this, setter));
            b.AddComponentParameter(_s++, "Placeholder", placeholder);
            if (inputType.HasValue)
                b.AddComponentParameter(_s++, "Type", inputType.Value);
            b.CloseComponent();
            b.CloseElement();
        }

        void RenderSelectField(RenderTreeBuilder b, string label, string value,
            Action<string> setter, string[] options)
        {
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "margin-top:12px");
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "font-size:13px;color:#333;margin-bottom:4px");
            b.AddContent(_s++, label);
            b.CloseElement();
            b.OpenComponent<Select<string, string>>(_s++);
            b.AddComponentParameter(_s++, "Value", value);
            b.AddComponentParameter(_s++, "ValueChanged",
                EventCallback.Factory.Create<string>(this, setter));
            b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
            {
                int _ = _s;
                foreach (var opt in options)
                {
                    b2.OpenComponent<SelectOption<string, string>>(_++);
                    b2.AddComponentParameter(_++, "Value", opt);
                    b2.AddComponentParameter(_++, "Label", opt);
                    b2.CloseComponent();
                }
            }));
            b.CloseComponent();
            b.CloseElement();
        }

        void RenderSliderField(RenderTreeBuilder b, string label, double value,
            Action<double> setter, double min, double max, double step, string suffix)
        {
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "margin-top:12px");
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "font-size:13px;color:#333;margin-bottom:4px");
            b.AddContent(_s++, label);
            b.CloseElement();
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "display:flex;align-items:center;gap:8px");
            b.OpenComponent<Slider<double>>(_s++);
            b.AddComponentParameter(_s++, "Value", value);
            b.AddComponentParameter(_s++, "ValueChanged",
                EventCallback.Factory.Create<double>(this, setter));
            b.AddComponentParameter(_s++, "Min", min);
            b.AddComponentParameter(_s++, "Max", max);
            b.AddComponentParameter(_s++, "Step", step);
            b.AddComponentParameter(_s++, "Style", "width:200px");
            b.CloseComponent();
            b.AddContent(_s++, $"{value:F1}{suffix}");
            b.CloseElement();
            b.CloseElement();
        }

        void RenderVoiceButtons(RenderTreeBuilder b, string title,
            (string label, string id)[] voices)
        {
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "margin-top:8px");
            b.OpenElement(_s++, "div");
            b.AddAttribute(_s++, "style", "display:flex;flex-wrap:wrap;gap:4px");
            foreach (var v in voices)
            {
                var voiceId = v.id; // 局部变量避免闭包共享
                b.OpenComponent<Button>(_s++);
                b.AddComponentParameter(_s++, "Size", ButtonSize.Small);
                b.AddComponentParameter(_s++, "OnClick",
                    EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(
                        this, _ => Configuration!.VoiceId = voiceId));
                b.AddAttribute(_s++, "ChildContent", (RenderFragment)((b2) =>
                {
                    b2.AddContent(_s++, v.label);
                }));
                b.CloseComponent();
            }
            b.CloseElement();
            b.CloseElement();
        }
    }
}
